/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_openstudiomeasure_WRAP_H_
#define SWIG_openstudiomeasure_WRAP_H_

#include <map>
#include <string>


class SwigDirector_OSRunner : public openstudio::measure::OSRunner, public Swig::Director {

public:
    SwigDirector_OSRunner(PyObject *self,openstudio::WorkflowJSON const &workflow);
    virtual ~SwigDirector_OSRunner();
    virtual bool inSelection(openstudio::model::ModelObject const &modelObject) const;
    virtual std::map< std::string,openstudio::measure::OSArgument,std::less< std::string >,std::allocator< std::pair< std::string const,openstudio::measure::OSArgument > > > getUserInput(std::vector< openstudio::measure::OSArgument,std::allocator< openstudio::measure::OSArgument > > &arguments) const;
    virtual void prepareForMeasureRun(openstudio::measure::OSMeasure const &measure);
    virtual void registerError(std::string const &message);
    virtual bool registerWarning(std::string const &message);
    virtual bool registerInfo(std::string const &message);
    virtual void registerAsNotApplicable(std::string const &message);
    virtual void registerInitialCondition(std::string const &message);
    virtual void registerFinalCondition(std::string const &message);
    virtual void registerValue(std::string const &name,bool value);
    virtual void registerValue(std::string const &name,std::string const &displayName,bool value);
    virtual void registerValue(std::string const &name,double value);
    virtual void registerValue(std::string const &name,double value,std::string const &units);
    virtual void registerValue(std::string const &name,std::string const &displayName,double value);
    virtual void registerValue(std::string const &name,std::string const &displayName,double value,std::string const &units);
    virtual void registerValue(std::string const &name,int value);
    virtual void registerValue(std::string const &name,int value,std::string const &units);
    virtual void registerValue(std::string const &name,std::string const &displayName,int value);
    virtual void registerValue(std::string const &name,std::string const &displayName,int value,std::string const &units);
    virtual void registerValue(std::string const &name,std::string const &value);
    virtual void registerValue(std::string const &name,std::string const &displayName,std::string const &value);
    virtual void haltWorkflow(std::string const &completedStatus="Invalid");
    virtual void createProgressBar(std::string const &text) const;
    virtual void updateProgress(double value) const;
    virtual void destroyProgressBar() const;

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class OSRunner doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[26];
#endif

};


class SwigDirector_OSMeasure : public openstudio::measure::OSMeasure, public Swig::Director {

public:
    SwigDirector_OSMeasure(PyObject *self);
    virtual ~SwigDirector_OSMeasure();
    virtual std::string name() const;
    virtual std::string description() const;
    virtual std::string taxonomy() const;
    virtual std::string modeler_description() const;
    virtual bool registerWithSketchUp() const;
    virtual bool registerWithApplication() const;

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class OSMeasure doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[6];
#endif

};


class SwigDirector_ModelMeasure : public openstudio::measure::ModelMeasure, public Swig::Director {

public:
    SwigDirector_ModelMeasure(PyObject *self);
    virtual ~SwigDirector_ModelMeasure();
    virtual std::string name() const;
    virtual std::string description() const;
    virtual std::string taxonomy() const;
    virtual std::string modeler_description() const;
    virtual bool registerWithSketchUp() const;
    virtual bool registerWithApplication() const;
    virtual std::vector< openstudio::measure::OSArgument,std::allocator< openstudio::measure::OSArgument > > arguments(openstudio::model::Model const &model) const;
    virtual std::vector< openstudio::measure::OSOutput,std::allocator< openstudio::measure::OSOutput > > outputs() const;
    virtual bool run(openstudio::model::Model &model,openstudio::measure::OSRunner &runner,std::map< std::string,openstudio::measure::OSArgument,std::less< std::string >,std::allocator< std::pair< std::string const,openstudio::measure::OSArgument > > > const &user_arguments) const;

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class ModelMeasure doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[9];
#endif

};


class SwigDirector_EnergyPlusMeasure : public openstudio::measure::EnergyPlusMeasure, public Swig::Director {

public:
    SwigDirector_EnergyPlusMeasure(PyObject *self);
    virtual ~SwigDirector_EnergyPlusMeasure();
    virtual std::string name() const;
    virtual std::string description() const;
    virtual std::string taxonomy() const;
    virtual std::string modeler_description() const;
    virtual bool registerWithSketchUp() const;
    virtual bool registerWithApplication() const;
    virtual std::vector< openstudio::measure::OSArgument,std::allocator< openstudio::measure::OSArgument > > arguments(openstudio::Workspace const &workspace) const;
    virtual std::vector< openstudio::measure::OSOutput,std::allocator< openstudio::measure::OSOutput > > outputs() const;
    virtual bool run(openstudio::Workspace &workspace,openstudio::measure::OSRunner &runner,std::map< std::string,openstudio::measure::OSArgument,std::less< std::string >,std::allocator< std::pair< std::string const,openstudio::measure::OSArgument > > > const &user_arguments) const;

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class EnergyPlusMeasure doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[9];
#endif

};


class SwigDirector_ReportingMeasure : public openstudio::measure::ReportingMeasure, public Swig::Director {

public:
    SwigDirector_ReportingMeasure(PyObject *self);
    virtual ~SwigDirector_ReportingMeasure();
    virtual std::string name() const;
    virtual std::string description() const;
    virtual std::string taxonomy() const;
    virtual std::string modeler_description() const;
    virtual bool registerWithSketchUp() const;
    virtual bool registerWithApplication() const;
    virtual std::vector< openstudio::measure::OSArgument,std::allocator< openstudio::measure::OSArgument > > arguments(openstudio::model::Model const &model) const;
    virtual std::vector< openstudio::measure::OSOutput,std::allocator< openstudio::measure::OSOutput > > outputs() const;
    virtual bool run(openstudio::measure::OSRunner &runner,std::map< std::string,openstudio::measure::OSArgument,std::less< std::string >,std::allocator< std::pair< std::string const,openstudio::measure::OSArgument > > > const &user_arguments) const;
    virtual std::vector< openstudio::IdfObject,std::allocator< openstudio::IdfObject > > energyPlusOutputRequests(openstudio::measure::OSRunner &runner,std::map< std::string,openstudio::measure::OSArgument,std::less< std::string >,std::allocator< std::pair< std::string const,openstudio::measure::OSArgument > > > const &user_arguments) const;

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class ReportingMeasure doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[10];
#endif

};


#endif
