/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_openstudioutilitiesplot_WRAP_H_
#define SWIG_openstudioutilitiesplot_WRAP_H_

#include <map>
#include <string>


class SwigDirector_ProgressBar : public openstudio::ProgressBar, public Swig::Director {

public:
    SwigDirector_ProgressBar(PyObject *self);
    virtual ~SwigDirector_ProgressBar();
    virtual int minimum() const;
    virtual void setMinimum(int min);
    virtual int maximum() const;
    virtual void setMaximum(int max);
    virtual int value() const;
    virtual std::string windowTitle() const;
    virtual void setWindowTitle(std::string const &title);
    virtual std::string text() const;
    virtual bool isVisible() const;
    virtual void setVisible(bool visible);
    virtual void onPercentageUpdated(double percentage);
    virtual void setRange(int min,int max);
    virtual void setValue(int value);

/* Internal director utilities */
public:
    bool swig_get_inner(const char *swig_protected_method_name) const {
      std::map<std::string, bool>::const_iterator iv = swig_inner.find(swig_protected_method_name);
      return (iv != swig_inner.end() ? iv->second : false);
    }
    void swig_set_inner(const char *swig_protected_method_name, bool swig_val) const {
      swig_inner[swig_protected_method_name] = swig_val;
    }
private:
    mutable std::map<std::string, bool> swig_inner;

#if defined(SWIG_PYTHON_DIRECTOR_VTABLE)
/* VTable implementation */
    PyObject *swig_get_method(size_t method_index, const char *method_name) const {
      PyObject *method = vtable[method_index];
      if (!method) {
        swig::SwigVar_PyObject name = SWIG_Python_str_FromChar(method_name);
        method = PyObject_GetAttr(swig_get_self(), name);
        if (!method) {
          std::string msg = "Method in class ProgressBar doesn't exist, undefined ";
          msg += method_name;
          Swig::DirectorMethodException::raise(msg.c_str());
        }
        vtable[method_index] = method;
      }
      return method;
    }
private:
    mutable swig::SwigVar_PyObject vtable[13];
#endif

};


#endif
