/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_OpenStudio_WRAP_H_
#define SWIG_OpenStudio_WRAP_H_

namespace Swig {
  class Director;
}


class SwigDirector_ProgressBar : public openstudio::ProgressBar, public Swig::Director {

public:
    SwigDirector_ProgressBar(VALUE self);
    virtual ~SwigDirector_ProgressBar();
    virtual int minimum() const;
    virtual void setMinimum(int min);
    virtual int maximum() const;
    virtual void setMaximum(int max);
    virtual int value() const;
    virtual std::string windowTitle() const;
    virtual void setWindowTitle(std::string const &title);
    virtual std::string text() const;
    virtual bool isVisible() const;
    virtual void setVisible(bool visible);
    virtual void onPercentageUpdated(double percentage);
    virtual void setRange(int min,int max);
    virtual void setValue(int value);
};


#endif
