/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_OpenStudio__Model_WRAP_H_
#define SWIG_OpenStudio__Model_WRAP_H_

namespace Swig {
  class Director;
}


class SwigDirector_Model : public openstudio::model::Model, public Swig::Director {

public:
    SwigDirector_Model(VALUE self);
    SwigDirector_Model(VALUE self,openstudio::IdfFile const &idfFile);
    SwigDirector_Model(VALUE self,openstudio::Workspace const &workspace);
    SwigDirector_Model(VALUE self,openstudio::model::Model const &other);
    SwigDirector_Model(VALUE self,openstudio::model::Model &&other);
    SwigDirector_Model(VALUE self,std::shared_ptr< openstudio::model::detail::Model_Impl > impl);
    virtual ~SwigDirector_Model();
    virtual void addVersionObject();
    virtual void addVersionObjectSwigPublic() {
      openstudio::model::Model::addVersionObject();
    }
};


#endif
